WITH BOOK_TOTAL_SALES AS (
    SELECT BOOK.BOOK_ID, SUM(SALES * PRICE) AS SALES
    FROM BOOK_SALES
    JOIN BOOK
    ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK.BOOK_ID
) 

SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BOOK_TOTAL_SALES.SALES) AS TOTAL_SALES
FROM BOOK
JOIN AUTHOR 
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_TOTAL_SALES
ON BOOK.BOOK_ID = BOOK_TOTAL_SALES.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC