WITH RECURSIVE ECOLI_GENERATION (ID, GENERATION) AS (
    SELECT ID, 1
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CHILD.ID, PARENT.GENERATION + 1
    FROM ECOLI_DATA AS CHILD
    JOIN ECOLI_GENERATION AS PARENT ON CHILD.PARENT_ID = PARENT.ID
)

SELECT ID
FROM ECOLI_GENERATION
WHERE GENERATION = 3
ORDER BY ID