WITH FIRST_GENERATION_ID AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GENERATION_ID AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (
        SELECT ID 
        FROM FIRST_GENERATION_ID
    )
)

SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (
    SELECT ID
    FROM SECOND_GENERATION_ID
)
ORDER BY ID