-- 상품 코드(PRODUCT_ID)별 총 판매량(SALES_AMOUNT) 구하기 --
WITH TOTAL_OFFLINE_SALE AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT PRODUCT_CODE, (PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT 
JOIN TOTAL_OFFLINE_SALE 
ON PRODUCT.PRODUCT_ID = TOTAL_OFFLINE_SALE.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE