SELECT
    PRODUCT_CODE,
    PRICE * TOTAL_SALES AS SALES -- 상품별 매출액
FROM PRODUCT
JOIN ( -- 상품별 판매량 합계
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS PRODUCT_SALES
ON PRODUCT.PRODUCT_ID = PRODUCT_SALES.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC