WITH FISH_INFO_REMOVED_NULL AS (
    SELECT ID, 
           (CASE
               WHEN LENGTH IS NULL THEN 10
               ELSE LENGTH
           END) AS LENGTH
    FROM FISH_INFO
)

SELECT ROUND(AVG(LENGTH), 2) AS AVERAGE_LENGTH
FROM FISH_INFO_REMOVED_NULL