WITH SEDAN_AND_SUV_CARS AS ( -- 세단 또는 SUV 차량 목록
  SELECT CAR_ID, CAR_TYPE, DAILY_FEE
  FROM CAR_RENTAL_COMPANY_CAR
  WHERE CAR_TYPE REGEXP '^(세단|SUV)'
), SEDAN_SUV_DISCOUNT_30 AS ( -- 세단 또는 SUV 차량의 '30일 이상' 대여 할인 정책
  SELECT CAR_TYPE, DISCOUNT_RATE
  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
  WHERE CAR_TYPE REGEXP '^(세단|SUV)' 
    AND DURATION_TYPE = '30일 이상'
), AVAILABLE_CARS_IN_NOVEMBER AS ( -- 2022년 11월 1일부터 30일까지 전 기간 동안 대여 가능한 차량
  SELECT CAR_ID
  FROM SEDAN_AND_SUV_CARS
  WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
      AND END_DATE >= '2022-11-01'
  )
)

SELECT SEDAN_AND_SUV_CARS.CAR_ID, 
       SEDAN_AND_SUV_CARS.CAR_TYPE, 
       ROUND(DAILY_FEE * (1 - 0.01 * DISCOUNT_RATE) * 30) AS FEE
FROM AVAILABLE_CARS_IN_NOVEMBER
JOIN SEDAN_AND_SUV_CARS
USING (CAR_ID)
JOIN SEDAN_SUV_DISCOUNT_30
USING (CAR_TYPE)
WHERE ROUND(DAILY_FEE * (1 - 0.01 * DISCOUNT_RATE) * 30) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC