-- CAR_RENTAL_COMPANY_CAR: 자동차 정보
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: 대여 기록 -> 22년 11월 한 달 동안 대여할 수 있는가?
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN: 할인 정보 -> 30일 이상 할인율은 얼마인가?

SELECT 
    CAR.CAR_ID, 
    CAR.CAR_TYPE, 
    FLOOR(
        CAR.DAILY_FEE * 30 * (1 - DISCOUNT.DISCOUNT_RATE / 100)
    ) AS FEE
FROM (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    WHERE CAR_TYPE IN ('세단', 'SUV') -- 세단 또는 SUV만 포함
    AND NOT EXISTS ( -- 대여 기간 중 11월이 포함되어 있는 자동차 제외
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE C.CAR_ID = H.CAR_ID
        AND H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
    )
) AS CAR
JOIN ( -- 30일 이상 할인율 적용
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) AS DISCOUNT ON CAR.CAR_TYPE = DISCOUNT.CAR_TYPE
WHERE FLOOR(CAR.DAILY_FEE * 30 * (1 - DISCOUNT.DISCOUNT_RATE / 100)) >= 500000
AND FLOOR(CAR.DAILY_FEE * 30 * (1 - DISCOUNT.DISCOUNT_RATE / 100)) < 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC