select REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FAVORITES
from REST_INFO
join (
    select FOOD_TYPE, max(FAVORITES) as MAX_FAVORITES
    from REST_INFO
    group by FOOD_TYPE
) as MAX_REST_INFO
on REST_INFO.FOOD_TYPE = MAX_REST_INFO.FOOD_TYPE
and REST_INFO.FAVORITES = MAX_REST_INFO.MAX_FAVORITES
order by FOOD_TYPE desc