SELECT ID, 
CASE 
    WHEN ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) <= TOTAL * 0.25 THEN 'CRITICAL' 
    WHEN ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) <= TOTAL * 0.5 THEN 'HIGH' 
    WHEN ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) <= TOTAL * 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID, SIZE_OF_COLONY, COUNT(*) OVER () AS TOTAL 
    FROM ECOLI_DATA
) AS SUB_QUERY
ORDER BY ID
    