SELECT
    ANIMAL_OUTS.ANIMAL_ID, 
    ANIMAL_OUTS.ANIMAL_TYPE, 
    ANIMAL_OUTS.NAME
FROM ANIMAL_INS
JOIN ANIMAL_OUTS 
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
AND ( -- 보호소 들어올 당시에는 중성화되지 않음
    ANIMAL_INS.SEX_UPON_INTAKE NOT LIKE 'Spayed%' 
    AND 
    ANIMAL_INS.SEX_UPON_INTAKE NOT LIKE 'Neutered%'
)
AND ( -- 보호소 나갈 당시에는 중성화됨
    ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%' 
    OR 
    ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%'
)
ORDER BY ANIMAL_OUTS.ANIMAL_ID ASC