WITH USER_JOINED_2021 AS ( -- 2021년에 가입한 회원 정보
  SELECT USER_ID
  FROM USER_INFO
  WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'  
)

SELECT YEAR(SALES_DATE) AS YEAR, 
       MONTH(SALES_DATE) AS MONTH,
       COUNT(DISTINCT USERS.USER_ID) AS PURCHASED_USERS, -- 해당 연, 월에 상품을 구매한 회원 수
       ROUND(1.0 * COUNT(DISTINCT USERS.USER_ID) / (SELECT COUNT(*) FROM USER_JOINED_2021), 1) AS PURCHASED_RATIO
FROM USER_JOINED_2021 AS USERS
JOIN ONLINE_SALE AS SALE
USING (USER_ID)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH