WITH RECURSIVE ECOLI_HIERARCHY (ID, GENERATION) AS (
    SELECT ID, 1
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL -- 최상위 노드
    
    UNION ALL
    
    SELECT CHILD.ID, PARENT.GENERATION + 1
    FROM ECOLI_DATA AS CHILD
    JOIN ECOLI_HIERARCHY AS PARENT ON CHILD.PARENT_ID = PARENT.ID
)

SELECT COUNT(ECOLI_HIERARCHY.ID) AS COUNT, GENERATION
FROM ECOLI_HIERARCHY
LEFT OUTER JOIN ECOLI_DATA ON ECOLI_HIERARCHY.ID = ECOLI_DATA.PARENT_ID
WHERE ECOLI_DATA.PARENT_ID IS NULL -- 다른 대장균의 부모가 아님
GROUP BY GENERATION
ORDER BY GENERATION