WITH RECURSIVE ECOLI_GENERATIONS AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CHILD.ID, PARENT.ID, GENERATION + 1
    FROM ECOLI_GENERATIONS AS PARENT
    JOIN ECOLI_DATA AS CHILD ON CHILD.PARENT_ID = PARENT.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION 
FROM ECOLI_GENERATIONS
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_GENERATIONS
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION