WITH RECURSIVE ECOLI_HIERARCHY (ID, PARENT_ID, GENERATION) AS (
  SELECT ID, PARENT_ID, 1
  FROM ECOLI_DATA 
  WHERE PARENT_ID IS NULL
    
  UNION ALL
    
  SELECT CHILD.ID, CHILD.PARENT_ID, PARENT.GENERATION + 1
  FROM ECOLI_DATA AS CHILD
  JOIN ECOLI_HIERARCHY AS PARENT ON CHILD.PARENT_ID = PARENT.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM ECOLI_HIERARCHY 
WHERE ID NOT IN ( -- 다른 대장균의 부모가 되는 대장균 제외
  SELECT DISTINCT PARENT_ID 
  FROM ECOLI_HIERARCHY 
  WHERE PARENT_ID IS NOT NULL -- NOT IN 사용 시 NULL로 인한 예외 방지
)
GROUP BY GENERATION
ORDER BY GENERATION