WITH QUARTER_DATA AS ( -- 분기 정보 테이블
  SELECT ID, CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3), 'Q') AS QUARTER
  FROM ECOLI_DATA 
)

SELECT QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM QUARTER_DATA
GROUP BY QUARTER
ORDER BY QUARTER