SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_INS

-- 동물 보호소에 들어온 기록은 있지만 입양 보낸 기록은 없음
LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.ANIMAL_ID IS NULL

ORDER BY ANIMAL_INS.DATETIME ASC
LIMIT 3