SELECT 
    FO.PRODUCT_ID, 
    FP.PRODUCT_NAME, 
    FP.PRICE * FO.TOTAL_AMOUNT AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
) AS FO
JOIN FOOD_PRODUCT AS FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC