SELECT PRODUCT.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS PRODUCT
JOIN FOOD_ORDER AS ORDERS
ON PRODUCT.PRODUCT_ID = ORDERS.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT.PRODUCT_ID