WITH JULY_ORDERS AS ( -- 7월 아이스크림별 총 주문량
  SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
  FROM JULY
  GROUP BY FLAVOR
)

SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF 
JOIN JULY_ORDERS
ON FIRST_HALF.FLAVOR = JULY_ORDERS.FLAVOR
ORDER BY (FIRST_HALF.TOTAL_ORDER + JULY_ORDERS.TOTAL_ORDER) DESC
LIMIT 3