SELECT APNT_NO, PT_NAME, PATIENT.PT_NO, DOCTOR.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT
JOIN APPOINTMENT
ON PATIENT.PT_NO = APPOINTMENT.PT_NO
JOIN DOCTOR
ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
WHERE DATE(APNT_YMD) = '2022-04-13'
AND DOCTOR.MCDP_CD = 'CS'
AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD