WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOUR_TABLE WHERE HOUR < 23
),

GROUPING_TABLE AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)

SELECT HOUR_TABLE.HOUR, IFNULL(GROUPING_TABLE.COUNT, 0) AS COUNT
FROM HOUR_TABLE
LEFT JOIN GROUPING_TABLE 
ON HOUR_TABLE.HOUR = GROUPING_TABLE.HOUR;