WITH FRONTEND AS ( -- 전체 프론트엔드 스킬 코드 테이블
  SELECT BIT_OR(CODE) AS CODES
  FROM SKILLCODES 
  WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
JOIN FRONTEND
ON (DEVELOPERS.SKILL_CODE & FRONTEND.CODES) != 0 -- 프론트엔드 스킬을 적어도 하나 가지고 있음
ORDER BY ID