select USER_ID, NICKNAME, sum(PRICE) as TOTAL_SALES
from USED_GOODS_USER as USERS
join USED_GOODS_BOARD as BOARD
on USERS.USER_ID = BOARD.WRITER_ID
where STATUS = 'DONE'
group by USER_ID
having sum(PRICE) >= 700000
order by TOTAL_SALES