WITH REVIEWS AS ( -- 회원별 리뷰 개수를 구한 테이블
  SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT
  FROM REST_REVIEW
  GROUP BY MEMBER_ID
), RANKED AS ( -- 리뷰 개수를 기준으로 회원별 순위를 매긴 테이블
  SELECT MEMBER_ID, RANK() OVER (ORDER BY REVIEW_COUNT DESC) AS RANK_NUM
  FROM REVIEWS 
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MEMBER
JOIN REST_REVIEW AS REVIEW
ON MEMBER.MEMBER_ID = REVIEW.MEMBER_ID
JOIN RANKED
ON MEMBER.MEMBER_ID = RANKED.MEMBER_ID
WHERE RANK_NUM = 1 -- 리뷰를 가장 많이 작성한 회원의 리뷰만 조회
ORDER BY REVIEW_DATE, REVIEW_TEXT