SELECT 
    MEMBER.MEMBER_NAME, 
    REVIEW.REVIEW_TEXT, 
    REVIEW.REVIEW_DATE
FROM (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID) = ( -- 최대 리뷰 개수
        SELECT COUNT(REVIEW_ID)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY 1 DESC
        LIMIT 1
    )
) AS MAX_REVIEW_MEMBER
JOIN MEMBER_PROFILE AS MEMBER ON MAX_REVIEW_MEMBER.MEMBER_ID = MEMBER.MEMBER_ID
JOIN REST_REVIEW AS REVIEW ON MAX_REVIEW_MEMBER.MEMBER_ID = REVIEW.MEMBER_ID
ORDER BY 3 ASC, 2 ASC