SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS CHILD, ECOLI_DATA AS PARENT
WHERE (CHILD.PARENT_ID = PARENT.ID) AND (CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE)
ORDER BY CHILD.ID