WITH MAX_SIZE_BY_YEAR AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT 
    YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) AS YEAR, 
    MAX_SIZE_BY_YEAR.SIZE_OF_COLONY - ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV, 
    ECOLI_DATA.ID
FROM 
    ECOLI_DATA, 
    MAX_SIZE_BY_YEAR 
WHERE 
    YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MAX_SIZE_BY_YEAR.YEAR
ORDER BY 
    YEAR(ECOLI_DATA.DIFFERENTIATION_DATE),
    MAX_SIZE_BY_YEAR.SIZE_OF_COLONY - ECOLI_DATA.SIZE_OF_COLONY