WITH MAX_RESULT AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY 
        YEAR(DIFFERENTIATION_DATE)
)

SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (MAX_RESULT.MAX_SIZE - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV, 
    ID
FROM 
    ECOLI_DATA
JOIN 
    MAX_RESULT
ON 
    YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MAX_RESULT.YEAR
ORDER BY
    YEAR, 
    YEAR_DEV