SELECT DISTINCT CAR.CAR_ID -- 자동차 ID 리스트에서 중복 제거
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR_TYPE = '세단' -- 종류가 '세단'인 자동차만
AND MONTH(START_DATE) = 10 -- 10월에 대여를 시작한 기록이 있는 자동차만
ORDER BY CAR.CAR_ID DESC -- 자동차 ID를 기준으로 내림차순 정렬