WITH FISH_LENGTH_RANK_PER_TYPE AS ( -- 물고기 종류별 크기 순위
  SELECT ID, 
         FISH_NAME, 
         LENGTH, 
         RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS LENGTH_RANK
  FROM FISH_INFO
  JOIN FISH_NAME_INFO USING (FISH_TYPE)
)

SELECT ID, FISH_NAME, LENGTH
FROM FISH_LENGTH_RANK_PER_TYPE
WHERE LENGTH_RANK = 1 -- 물고기 종류별 크기 순위가 1위인 물고기만 조회
ORDER BY ID