SELECT FISH_INFO.ID, FISH_NAME, MAXIMUM_FISH.LENGTH
FROM FISH_INFO JOIN (
                    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
                    FROM FISH_INFO
                    GROUP BY FISH_TYPE
                    ) MAXIMUM_FISH ON FISH_INFO.FISH_TYPE = MAXIMUM_FISH.FISH_TYPE
               JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE FISH_INFO.LENGTH = MAXIMUM_FISH.LENGTH
