WITH MAX_FISH_INFO AS (
    SELECT FISH_INFO.FISH_TYPE, FISH_NAME, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    JOIN FISH_NAME_INFO
    ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
    GROUP BY FISH_TYPE, FISH_NAME
)

SELECT ID, FISH_NAME, MAX_FISH_INFO.LENGTH
FROM FISH_INFO 
JOIN MAX_FISH_INFO
ON FISH_INFO.FISH_TYPE = MAX_FISH_INFO.FISH_TYPE
AND FISH_INFO.LENGTH = MAX_FISH_INFO.LENGTH
ORDER BY ID