WITH FRONTEND AS ( -- 프론트엔드 기술 코드 --
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
), CSHARP AS ( -- C# 기술 코드 --
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
), PYTHON AS ( -- Python 기술 코드 --
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
)

SELECT
    CASE
        WHEN DEV.SKILL_CODE & FRONTEND.CODE AND DEV.SKILL_CODE & PYTHON.CODE THEN 'A'
        WHEN DEV.SKILL_CODE & CSHARP.CODE THEN 'B'
        WHEN DEV.SKILL_CODE & FRONTEND.CODE THEN 'C'
        ELSE NULL
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS AS DEV, FRONTEND, PYTHON, CSHARP
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID