SELECT 
    BOOK.BOOK_ID, 
    AUTHOR.AUTHOR_NAME, 
    BOOK.PUBLISHED_DATE
FROM (
    SELECT BOOK_ID, AUTHOR_ID, PUBLISHED_DATE
    FROM BOOK
    WHERE CATEGORY = '경제'
) AS BOOK
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY 3 ASC